spring:
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/tnk_gesture_prod
    username: prod_user
    password: my-secret-pw
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
